import React, { useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';

const faqs = [
  {
    question: 'How does Lineage analyze my Tai Chi movements?',
    answer: 'Lineage uses advanced computer vision and machine learning algorithms trained on authentic Yang Family Tai Chi principles. The AI analyzes your posture, movement flow, timing, and energy expression, comparing them to traditional standards to provide specific feedback on areas like rooting, qi circulation, and form accuracy.'
  },
  {
    question: 'Can Lineage replace my Tai Chi instructor?',
    answer: 'No, Lineage is designed to complement, not replace, your instructor. We believe in scaling the wisdom of masters, not replacing them. Lineage bridges the gap between classes, helping you maintain proper practice and progress faster, while your instructor provides the human connection and deeper teachings essential to martial arts.'
  },
  {
    question: 'What makes Lineage different from other fitness apps?',
    answer: 'Lineage is specifically built for traditional, lineage-based martial arts, starting with Yang Family Tai Chi. Unlike generic fitness apps, we focus on authentic principles, provide personalized feedback based on traditional standards, and create meaningful connections between your home practice and classroom instruction.'
  },
  {
    question: 'How accurate is the AI feedback?',
    answer: 'Our AI has been trained on thousands of hours of authentic Yang Family Tai Chi demonstrations and validated by experienced masters. While it cannot replace human intuition, it provides remarkably accurate feedback on technical aspects like posture, balance, and movement quality, with accuracy rates above 85% for core principles like rooting stability.'
  },
  {
    question: 'Do I need special equipment to use Lineage?',
    answer: 'No special equipment is needed. Lineage works with any smartphone or tablet camera. Simply position your device to capture your practice space, and the AI will analyze your movements in real-time. For best results, ensure good lighting and a clear view of your full body.'
  },
  {
    question: 'What is a "Personalized Learning Arc"?',
    answer: 'A Personalized Learning Arc is your custom 30-day training plan generated by AI based on your current skill level, progress rate, and specific areas needing improvement. It adapts as you grow, ensuring each practice session is purposeful and aligned with your development goals.'
  },
  {
    question: 'Can beginners use Lineage effectively?',
    answer: 'Absolutely! Lineage is designed for all levels, from complete beginners to advanced practitioners. For beginners, it provides gentle guidance and builds confidence through clear, step-by-step instruction. The AI adapts its feedback complexity to match your experience level.'
  },
  {
    question: 'How does Lineage connect with my instructor?',
    answer: 'Lineage can capture and integrate feedback from your instructor to inform your digital profile. Your instructor can also track your progress and adjust their teaching based on your home practice data, creating a seamless connection between classroom and personal practice.'
  }
];

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="py-20 bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-4xl lg:text-5xl font-bold text-gray-900 mb-6">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-gray-600">
            Everything you need to know about AI-powered Tai Chi mentorship.
          </p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-shadow duration-200"
            >
              <button
                className="w-full px-6 py-6 text-left flex items-center justify-between hover:bg-gray-50 transition-colors duration-200"
                onClick={() => toggleFAQ(index)}
              >
                <h3 className="text-lg font-semibold text-gray-900 pr-4">
                  {faq.question}
                </h3>
                <div className="flex-shrink-0">
                  {openIndex === index ? (
                    <ChevronUp className="w-5 h-5 text-emerald-600" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-gray-400" />
                  )}
                </div>
              </button>
              
              {openIndex === index && (
                <div className="px-6 pb-6">
                  <div className="border-t border-gray-100 pt-4">
                    <p className="text-gray-600 leading-relaxed">
                      {faq.answer}
                    </p>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Contact CTA */}
        <div className="mt-16 text-center">
          <div className="bg-gradient-to-r from-emerald-600 to-teal-500 rounded-2xl p-8 text-white">
            <h3 className="text-2xl font-bold mb-4">
              Ready to Begin Your Journey?
            </h3>
            <p className="text-lg opacity-90 mb-6">
              Join the community of practitioners transforming their Tai Chi practice with AI guidance.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button className="bg-white text-emerald-600 px-6 py-3 rounded-lg font-semibold hover:bg-gray-50 transition-colors duration-200">
                Start Free Trial
              </button>
              <button className="border-2 border-white text-white px-6 py-3 rounded-lg font-semibold hover:bg-white hover:text-emerald-600 transition-all duration-200">
                Contact Master
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQ;